# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5d5fc93e375238e8147f40f6f04bef127f8c937b0c564ce6adf8564d18cc764c44b14b7cdddd7ca0b8f6adf7610f22ac8f84bad6327768f0c73772ea6a56f89

test:
  secret_key_base: df1a80ab07c9a07501379669f688bd63904fcdb3c399942a0ad2feccf5e409c28de1bc12a0cec0d457d83551f50d807e33668f76235143bf62b7a855b4c402bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
